BLANCO = (255, 255, 255)
NEGRO = (0, 0, 0)
IRIS_NORMAL = (50, 100, 150)
ROSA_AMOR = (255, 100, 180) 
VERDE_DINERO = (50, 200, 50) 

# Cantidad de frames del gif de parpadeo (archivos en /media)
CANTIDAD_FRAMES = 5
ANGULO_LOGO = 0

# --- DIMENSIONES VIRTUALES ---
RES_VIRTUAL = (160, 120)
ANCHO_REAL, ALTO_REAL = 640, 480

# --- TAMAÑOS DE PUPILA (RADIO_TARGET) ---
RADIO_PUPILA_BASE = 16
RADIO_PUPILA_AMOR = 24
RADIO_PUPILA_DINERO = 25
RADIO_PUPILA_LOGO = 40
RADIO_PUPILA_DROGADO = 8
RADIO_PUPILA_MAS = 30
RADIO_PUPILA_MENOS = 8

# ====
FPS_OBJETIVO = 60
DISTANCIA_MOVIMIENTO = 30
DEADZONE_JOYSTICK = 0.3

GLITCH_INTERVAL_MS = 45

# ==== Botones asignados a cada estado
BTN_MAS = 0
BTN_MENOS = 1
BTN_AMOR = 2
BTN_DINERO = 3
BTN_LOGO = 4
BTN_DROGADO = 5
BTN_GLITCH = 6

MODO_FULLSCREEN = False
MOSTRAR_CURSOR = False

JOYSTICK_RESCAN_INTERVAL_MS = 3000
INPUT_WATCHDOG_MS = 10000
JOYSTICK_RECOVERY_COOLDOWN_MS = 8000
LOG_INPUT_HEARTBEAT_MS = 5000